-- =====================================================
-- SCHEMA COMPLETO - SISTEMA DE ABERTURA DE OS (SAOS)
-- =====================================================

-- Tabela de Usuários (Clientes e Técnicos)
CREATE TABLE USUARIOS (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(100) UNIQUE NOT NULL,
    TELEFONE VARCHAR(20),
    CPF_CNPJ VARCHAR(18) UNIQUE,
    TIPO_USUARIO VARCHAR(20) NOT NULL CHECK (TIPO_USUARIO IN ('CLIENTE', 'TECNICO', 'ADMIN')),
    EMPRESA VARCHAR(100),
    DEPARTAMENTO VARCHAR(50),
    CARGO VARCHAR(50),
    SENHA_HASH VARCHAR(255),
    ATIVO BOOLEAN DEFAULT TRUE,
    DTHR_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DTHR_ULTIMO_ACESSO TIMESTAMP
);

-- Tabela de Categorias de Solicitação
CREATE TABLE CATEGORIAS (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    DESCRICAO TEXT,
    COR VARCHAR(7) DEFAULT '#3B82F6',
    ICONE VARCHAR(50),
    ATIVO BOOLEAN DEFAULT TRUE,
    DTHR_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Prioridades
CREATE TABLE PRIORIDADES (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO TEXT,
    COR VARCHAR(7) NOT NULL,
    PRAZO_HORAS INTEGER NOT NULL,
    ESCALONAMENTO_HORAS INTEGER,
    ORDEM INTEGER NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE
);

-- Tabela de Status
CREATE TABLE STATUS (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    DESCRICAO blob,
    COR VARCHAR(7) NOT NULL,
    ICONE VARCHAR(50),
    FINALIZADO BOOLEAN DEFAULT FALSE,
    ORDEM INTEGER NOT NULL,
    ATIVO BOOLEAN DEFAULT TRUE
);

-- Tabela Principal de Solicitações (OS)
CREATE TABLE SOLICITACOES (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CODIGO_REFERENCIA VARCHAR(20) UNIQUE NOT NULL,
    TITULO VARCHAR(200) NOT NULL,
    DESCRICAO TEXT NOT NULL,
    ID_CLIENTE INTEGER NOT NULL,
    ID_CATEGORIA INTEGER NOT NULL,
    ID_PRIORIDADE INTEGER NOT NULL,
    ID_STATUS INTEGER NOT NULL,
    ID_TECNICO_RESPONSAVEL INTEGER,
    ID_TECNICO_CRIADOR INTEGER,
    SISTEMA VARCHAR(100),
    MODULO VARCHAR(100),
    PRAZO_RESOLUCAO TIMESTAMP,
    PRAZO_ESCALONAMENTO TIMESTAMP,
    DTHR_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DTHR_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DTHR_RESOLUCAO TIMESTAMP,
    DTHR_FECHAMENTO TIMESTAMP,
    AVALIACAO_CLIENTE INTEGER CHECK (AVALIACAO_CLIENTE BETWEEN 1 AND 5),
    COMENTARIO_AVALIACAO TEXT,
    URGENTE BOOLEAN DEFAULT FALSE,
    CONFIDENCIAL BOOLEAN DEFAULT FALSE,
    FOREIGN KEY (ID_CLIENTE) REFERENCES USUARIOS(ID),
    FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID),
    FOREIGN KEY (ID_PRIORIDADE) REFERENCES PRIORIDADES(ID),
    FOREIGN KEY (ID_STATUS) REFERENCES STATUS(ID),
    FOREIGN KEY (ID_TECNICO_RESPONSAVEL) REFERENCES USUARIOS(ID),
    FOREIGN KEY (ID_TECNICO_CRIADOR) REFERENCES USUARIOS(ID)
);

-- Tabela de Histórico de Interações
CREATE TABLE HISTORICO (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_SOLICITACAO INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    TIPO_ACAO VARCHAR(50) NOT NULL,
    DESCRICAO blob NOT NULL,
    DADOS_ANTERIORES blob,
    DADOS_NOVOS blob,
    DTHR_ACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    IP_ADDRESS VARCHAR(45),
    USER_AGENT blob,
    FOREIGN KEY (ID_SOLICITACAO) REFERENCES SOLICITACOES(ID),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

-- Tabela de Anexos
CREATE TABLE ANEXOS (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_SOLICITACAO INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    NOME_ORIGINAL VARCHAR(255) NOT NULL,
    NOME_ARQUIVO VARCHAR(255) NOT NULL,
    CAMINHO_ARQUIVO VARCHAR(500) NOT NULL,
    TIPO_MIME VARCHAR(100),
    TAMANHO_BYTES BIGINT,
    DESCRICAO blob,
    DTHR_UPLOAD TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_SOLICITACAO) REFERENCES SOLICITACOES(ID),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

-- Tabela de Comentários
CREATE TABLE COMENTARIOS (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_SOLICITACAO INTEGER NOT NULL,
    ID_USUARIO INTEGER NOT NULL,
    COMENTARIO blob NOT NULL,
    INTERNO BOOLEAN DEFAULT FALSE,
    DTHR_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DTHR_EDICAO TIMESTAMP,
    FOREIGN KEY (ID_SOLICITACAO) REFERENCES SOLICITACOES(ID),
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID)
);

-- Tabela de Templates de Email
CREATE TABLE TEMPLATES_EMAIL (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME VARCHAR(100) NOT NULL,
    ASSUNTO VARCHAR(200) NOT NULL,
    CORPO_HTML blob NOT NULL,
    CORPO_TEXTO blob,
    VARIAVEIS blob, -- JSON com variáveis disponíveis
    ATIVO BOOLEAN DEFAULT TRUE,
    DTHR_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DTHR_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Configurações do Sistema
CREATE TABLE CONFIGURACOES (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CHAVE VARCHAR(100) UNIQUE NOT NULL,
    VALOR blob,
    DESCRICAO blob,
    TIPO VARCHAR(20) DEFAULT 'TEXTO',
    DTHR_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DTHR_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- Tabela de Notificações
CREATE TABLE NOTIFICACOES (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ID_USUARIO INTEGER NOT NULL,
    ID_SOLICITACAO INTEGER,
    TIPO VARCHAR(50) NOT NULL,
    TITULO VARCHAR(200) NOT NULL,
    MENSAGEM blob NOT NULL,
    LIDA BOOLEAN DEFAULT FALSE,
    DTHR_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DTHR_LEITURA TIMESTAMP,
    FOREIGN KEY (ID_USUARIO) REFERENCES USUARIOS(ID),
    FOREIGN KEY (ID_SOLICITACAO) REFERENCES SOLICITACOES(ID)
);

-- Tabela de Knowledge Base
CREATE TABLE KNOWLEDGE_BASE (
    ID INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    TITULO VARCHAR(200) NOT NULL,
    CONTEUDO blob NOT NULL,
    CATEGORIA VARCHAR(100),
    TAGS blob, -- JSON array
    ID_AUTOR INTEGER NOT NULL,
    VISUALIZACOES INTEGER DEFAULT 0,
    AVALIACAO_MEDIA DECIMAL(3,2) DEFAULT 0,
    ATIVO BOOLEAN DEFAULT TRUE,
    DTHR_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DTHR_ATUALIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (ID_AUTOR) REFERENCES USUARIOS(ID)
);

-- =====================================================
-- DADOS INICIAIS
-- =====================================================

-- Inserir Prioridades Padrão
INSERT INTO PRIORIDADES (NOME, DESCRICAO, COR, PRAZO_HORAS, ESCALONAMENTO_HORAS, ORDEM) VALUES
('Baixa', 'Demandas não críticas que podem ser resolvidas em até 5 dias úteis', '#10B981', 120, 96, 1),
('Média', 'Demandas importantes que devem ser resolvidas em até 3 dias úteis', '#F59E0B', 72, 48, 2),
('Alta', 'Demandas críticas que devem ser resolvidas em até 24 horas', '#EF4444', 24, 12, 3),
('Urgente', 'Demandas extremamente críticas que devem ser resolvidas imediatamente', '#DC2626', 4, 2, 4);

-- Inserir Status Padrão
INSERT INTO STATUS (NOME, DESCRICAO, COR, ICONE, FINALIZADO, ORDEM) VALUES
('Aberto', 'Solicitação recém-criada e aguardando triagem', '#3B82F6', 'folder-open', FALSE, 1),
('Em Análise', 'Solicitação sendo analisada pela equipe técnica', '#8B5CF6', 'search', FALSE, 2),
('Em Progresso', 'Trabalho iniciado na resolução da solicitação', '#F59E0B', 'cog', FALSE, 3),
('Aguardando Cliente', 'Aguardando informações ou confirmação do cliente', '#EF4444', 'clock', FALSE, 4),
('Aguardando Aprovação', 'Aguardando aprovação para prosseguir', '#8B5CF6', 'check-circle', FALSE, 5),
('Resolvido', 'Solicitação resolvida e aguardando confirmação do cliente', '#10B981', 'check', FALSE, 6),
('Fechado', 'Solicitação finalizada e confirmada pelo cliente', '#059669', 'archive', TRUE, 7),
('Cancelado', 'Solicitação cancelada', '#6B7280', 'x-circle', TRUE, 8);

-- Inserir Categorias Padrão
INSERT INTO CATEGORIAS (NOME, DESCRICAO, COR, ICONE) VALUES
('Sistema', 'Problemas relacionados ao sistema principal', '#3B82F6', 'computer'),
('Acesso', 'Problemas de login, senha e permissões', '#EF4444', 'key'),
('Relatórios', 'Solicitações de relatórios e consultas', '#10B981', 'chart-bar'),
('Integração', 'Problemas com integrações entre sistemas', '#8B5CF6', 'link'),
('Performance', 'Problemas de lentidão e performance', '#F59E0B', 'speed'),
('Backup', 'Solicitações relacionadas a backup e restauração', '#059669', 'database'),
('Treinamento', 'Solicitações de treinamento e capacitação', '#EC4899', 'academic-cap'),
('Outros', 'Outras solicitações não categorizadas', '#6B7280', 'dots-horizontal');

-- Inserir Templates de Email Padrão
INSERT INTO TEMPLATES_EMAIL (NOME, ASSUNTO, CORPO_HTML, CORPO_TEXTO, VARIAVEIS) VALUES
('confirmacao_abertura', 
 'Sua solicitação #{codigo_referencia} foi registrada com sucesso',
 '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #3B82F6; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; background: #f9fafb; }
        .footer { text-align: center; padding: 20px; color: #6B7280; font-size: 12px; }
        .status { display: inline-block; padding: 5px 10px; border-radius: 15px; color: white; font-weight: bold; }
        .priority-high { background: #EF4444; }
        .priority-medium { background: #F59E0B; }
        .priority-low { background: #10B981; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Solicitação Registrada</h1>
        </div>
        <div class="content">
            <p>Olá {nome_cliente},</p>
            <p>Sua solicitação foi registrada com sucesso em nosso sistema.</p>
            
            <h3>Detalhes da Solicitação:</h3>
            <ul>
                <li><strong>Código:</strong> {codigo_referencia}</li>
                <li><strong>Título:</strong> {titulo}</li>
                <li><strong>Categoria:</strong> {categoria}</li>
                <li><strong>Prioridade:</strong> <span class="status priority-{prioridade_classe}">{prioridade}</span></li>
                <li><strong>Prazo Estimado:</strong> {prazo_estimado}</li>
            </ul>
            
            <p><strong>Descrição:</strong></p>
            <p>{descricao}</p>
            
            <p>Você receberá atualizações sobre o progresso de sua solicitação por email.</p>
            
            <p>Acompanhe sua solicitação através do link: <a href="{link_acompanhamento}">{link_acompanhamento}</a></p>
        </div>
        <div class="footer">
            <p>Este é um email automático, não responda a esta mensagem.</p>
        </div>
    </div>
</body>
</html>',
 'Sua solicitação #{codigo_referencia} foi registrada com sucesso

Detalhes:
- Código: {codigo_referencia}
- Título: {titulo}
- Categoria: {categoria}
- Prioridade: {prioridade}
- Prazo Estimado: {prazo_estimado}

Descrição: {descricao}

Acompanhe sua solicitação: {link_acompanhamento}',
 '["codigo_referencia", "nome_cliente", "titulo", "categoria", "prioridade", "prioridade_classe", "prazo_estimado", "descricao", "link_acompanhamento"]'),

('atualizacao_status',
 'Sua solicitação #{codigo_referencia} foi atualizada para {novo_status}',
 '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #10B981; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; background: #f9fafb; }
        .status { display: inline-block; padding: 5px 10px; border-radius: 15px; color: white; font-weight: bold; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Atualização de Status</h1>
        </div>
        <div class="content">
            <p>Olá {nome_cliente},</p>
            <p>Sua solicitação foi atualizada.</p>
            
            <h3>Detalhes da Atualização:</h3>
            <ul>
                <li><strong>Código:</strong> {codigo_referencia}</li>
                <li><strong>Novo Status:</strong> <span class="status" style="background: {cor_status}">{novo_status}</span></li>
                <li><strong>Responsável:</strong> {responsavel}</li>
                <li><strong>Data/Hora:</strong> {data_atualizacao}</li>
            </ul>
            
            <p><strong>Comentário:</strong></p>
            <p>{comentario}</p>
            
            <p>Acompanhe sua solicitação através do link: <a href="{link_acompanhamento}">{link_acompanhamento}</a></p>
        </div>
    </div>
</body>
</html>',
 'Sua solicitação #{codigo_referencia} foi atualizada para {novo_status}

Detalhes:
- Código: {codigo_referencia}
- Novo Status: {novo_status}
- Responsável: {responsavel}
- Data/Hora: {data_atualizacao}

Comentário: {comentario}

Acompanhe sua solicitação: {link_acompanhamento}',
 '["codigo_referencia", "nome_cliente", "novo_status", "cor_status", "responsavel", "data_atualizacao", "comentario", "link_acompanhamento"]'),

('solicitacao_informacoes',
 'Precisamos de mais informações - Solicitação #{codigo_referencia}',
 '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #F59E0B; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; background: #f9fafb; }
        .alert { background: #FEF3C7; border: 1px solid #F59E0B; padding: 15px; border-radius: 5px; margin: 15px 0; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Solicitação de Informações</h1>
        </div>
        <div class="content">
            <p>Olá {nome_cliente},</p>
            <p>Para processar sua solicitação, precisamos de informações adicionais.</p>
            
            <div class="alert">
                <h3>Informações Necessárias:</h3>
                <p>{informacoes_necessarias}</p>
            </div>
            
            <h3>Detalhes da Solicitação:</h3>
            <ul>
                <li><strong>Código:</strong> {codigo_referencia}</li>
                <li><strong>Título:</strong> {titulo}</li>
                <li><strong>Responsável:</strong> {responsavel}</li>
            </ul>
            
            <p>Por favor, responda este email com as informações solicitadas ou acesse o sistema para atualizar sua solicitação.</p>
            
            <p>Link para atualização: <a href="{link_atualizacao}">{link_atualizacao}</a></p>
        </div>
    </div>
</body>
</html>',
 'Precisamos de mais informações - Solicitação #{codigo_referencia}

Informações Necessárias:
{informacoes_necessarias}

Detalhes:
- Código: {codigo_referencia}
- Título: {titulo}
- Responsável: {responsavel}

Link para atualização: {link_atualizacao}',
 '["codigo_referencia", "nome_cliente", "titulo", "responsavel", "informacoes_necessarias", "link_atualizacao"]'),

('resolucao_concluida',
 'Sua solicitação #{codigo_referencia} foi resolvida - Por favor avalie nosso serviço',
 '<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <style>
        body { font-family: Arial, sans-serif; line-height: 1.6; color: #333; }
        .container { max-width: 600px; margin: 0 auto; padding: 20px; }
        .header { background: #10B981; color: white; padding: 20px; text-align: center; }
        .content { padding: 20px; background: #f9fafb; }
        .success { background: #D1FAE5; border: 1px solid #10B981; padding: 15px; border-radius: 5px; margin: 15px 0; }
        .rating { text-align: center; margin: 20px 0; }
        .star { font-size: 24px; color: #F59E0B; cursor: pointer; }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>Solicitação Resolvida</h1>
        </div>
        <div class="content">
            <p>Olá {nome_cliente},</p>
            <p>Sua solicitação foi resolvida com sucesso!</p>
            
            <div class="success">
                <h3>Resolução Concluída</h3>
                <p><strong>Solução:</strong> {solucao}</p>
                <p><strong>Responsável:</strong> {responsavel}</p>
                <p><strong>Data de Resolução:</strong> {data_resolucao}</p>
            </div>
            
            <h3>Detalhes da Solicitação:</h3>
            <ul>
                <li><strong>Código:</strong> {codigo_referencia}</li>
                <li><strong>Título:</strong> {titulo}</li>
                <li><strong>Tempo de Resolução:</strong> {tempo_resolucao}</li>
            </ul>
            
            <div class="rating">
                <h3>Avalie nosso serviço:</h3>
                <p>Clique no link abaixo para avaliar a qualidade do atendimento:</p>
                <p><a href="{link_avaliacao}" style="background: #3B82F6; color: white; padding: 10px 20px; text-decoration: none; border-radius: 5px;">Avaliar Serviço</a></p>
            </div>
            
            <p>Obrigado por escolher nossos serviços!</p>
        </div>
    </div>
</body>
</html>',
 'Sua solicitação #{codigo_referencia} foi resolvida com sucesso!

Solução: {solucao}
Responsável: {responsavel}
Data de Resolução: {data_resolucao}

Detalhes:
- Código: {codigo_referencia}
- Título: {titulo}
- Tempo de Resolução: {tempo_resolucao}

Avalie nosso serviço: {link_avaliacao}',
 '["codigo_referencia", "nome_cliente", "titulo", "solucao", "responsavel", "data_resolucao", "tempo_resolucao", "link_avaliacao"]');

-- Inserir Configurações Padrão
INSERT INTO CONFIGURACOES (CHAVE, VALOR, DESCRICAO, TIPO) VALUES
('EMAIL_FROM', 'suporte@empresa.com.br', 'Email remetente padrão', 'TEXTO'),
('EMAIL_SMTP_HOST', 'smtp.office365.com', 'Servidor SMTP', 'TEXTO'),
('EMAIL_SMTP_PORT', '587', 'Porta SMTP', 'NUMERO'),
('EMAIL_SMTP_USER', 'suporte@empresa.com.br', 'Usuário SMTP', 'TEXTO'),
('EMAIL_SMTP_PASS', '', 'Senha SMTP (configurar)', 'SENHA'),
('SISTEMA_NOME', 'SAOS - Sistema de Abertura de OS', 'Nome do sistema', 'TEXTO'),
('SISTEMA_URL', 'https://saos.empresa.com.br', 'URL base do sistema', 'TEXTO'),
('PRAZO_LEMBRETE_HORAS', '24', 'Horas antes do prazo para enviar lembrete', 'NUMERO'),
('ESCALONAMENTO_AUTOMATICO', 'true', 'Ativar escalonamento automático', 'BOOLEAN'),
('NOTIFICACAO_EMAIL', 'true', 'Ativar notificações por email', 'BOOLEAN'),
('NOTIFICACAO_SMS', 'false', 'Ativar notificações por SMS', 'BOOLEAN'),
('UPLOAD_MAX_SIZE', '10485760', 'Tamanho máximo de upload (bytes)', 'NUMERO'),
('UPLOAD_ALLOWED_TYPES', 'pdf,doc,docx,jpg,jpeg,png,gif', 'Tipos de arquivo permitidos', 'TEXTO');

-- =====================================================
-- ÍNDICES PARA PERFORMANCE
-- =====================================================

-- Índices para SOLICITACOES
CREATE INDEX IDX_SOLICITACOES_CODIGO ON SOLICITACOES(CODIGO_REFERENCIA);
CREATE INDEX IDX_SOLICITACOES_CLIENTE ON SOLICITACOES(ID_CLIENTE);
CREATE INDEX IDX_SOLICITACOES_STATUS ON SOLICITACOES(ID_STATUS);
CREATE INDEX IDX_SOLICITACOES_PRIORIDADE ON SOLICITACOES(ID_PRIORIDADE);
CREATE INDEX IDX_SOLICITACOES_TECNICO ON SOLICITACOES(ID_TECNICO_RESPONSAVEL);
CREATE INDEX IDX_SOLICITACOES_CRIACAO ON SOLICITACOES(DTHR_CRIACAO);
CREATE INDEX IDX_SOLICITACOES_PRAZO ON SOLICITACOES(PRAZO_RESOLUCAO);

-- Índices para HISTORICO
CREATE INDEX IDX_HISTORICO_SOLICITACAO ON HISTORICO(ID_SOLICITACAO);
CREATE INDEX IDX_HISTORICO_USUARIO ON HISTORICO(ID_USUARIO);
CREATE INDEX IDX_HISTORICO_ACAO ON HISTORICO(DTHR_ACAO);

-- Índices para NOTIFICACOES
CREATE INDEX IDX_NOTIFICACOES_USUARIO ON NOTIFICACOES(ID_USUARIO);
CREATE INDEX IDX_NOTIFICACOES_LIDA ON NOTIFICACOES(LIDA);
CREATE INDEX IDX_NOTIFICACOES_CRIACAO ON NOTIFICACOES(DTHR_CRIACAO);

-- Índices para ANEXOS
CREATE INDEX IDX_ANEXOS_SOLICITACAO ON ANEXOS(ID_SOLICITACAO);
CREATE INDEX IDX_ANEXOS_USUARIO ON ANEXOS(ID_USUARIO);

-- Índices para COMENTARIOS
CREATE INDEX IDX_COMENTARIOS_SOLICITACAO ON COMENTARIOS(ID_SOLICITACAO);
CREATE INDEX IDX_COMENTARIOS_CRIACAO ON COMENTARIOS(DTHR_CRIACAO);

-- =====================================================
-- TRIGGERS PARA AUTOMAÇÃO
-- =====================================================

-- Trigger para gerar código de referência automático
CREATE TRIGGER TR_SOLICITACOES_CODIGO_REF
ACTIVE BEFORE INSERT ON SOLICITACOES
AS
BEGIN
    IF (NEW.CODIGO_REFERENCIA IS NULL OR NEW.CODIGO_REFERENCIA = '') THEN
    BEGIN
        NEW.CODIGO_REFERENCIA = 'OS' || CAST(YEAR(CURRENT_DATE) AS VARCHAR(4)) || 
                               LPAD(CAST(MONTH(CURRENT_DATE) AS VARCHAR(2)), 2, '0') ||
                               LPAD(CAST(DAY(CURRENT_DATE) AS VARCHAR(2)), 2, '0') ||
                               LPAD(CAST(NEW.ID AS VARCHAR(10)), 6, '0');
    END
END;

-- Trigger para registrar histórico automático
CREATE TRIGGER TR_SOLICITACOES_HISTORICO
ACTIVE AFTER UPDATE ON SOLICITACOES
AS
BEGIN
    IF (OLD.ID_STATUS != NEW.ID_STATUS) THEN
    BEGIN
        INSERT INTO HISTORICO (ID_SOLICITACAO, ID_USUARIO, TIPO_ACAO, DESCRICAO, DADOS_ANTERIORES, DADOS_NOVOS)
        VALUES (NEW.ID, NEW.ID_TECNICO_RESPONSAVEL, 'MUDANCA_STATUS', 
                'Status alterado de ' || (SELECT NOME FROM STATUS WHERE ID = OLD.ID_STATUS) || 
                ' para ' || (SELECT NOME FROM STATUS WHERE ID = NEW.ID_STATUS),
                OLD.ID_STATUS, NEW.ID_STATUS);
    END
END;

-- Trigger para atualizar timestamp de atualização
CREATE TRIGGER TR_SOLICITACOES_UPDATE_TIME
ACTIVE BEFORE UPDATE ON SOLICITACOES
AS
BEGIN
    NEW.DTHR_ATUALIZACAO = CURRENT_TIMESTAMP;
END;
